#!/bin/bash
#
# Builds source and binary debian packages by compiling from source in a base chroot

# Replace plucky with target distro 
DIST=plucky

# optionally mount the cache dir as tmpfs for speed at the cost of a lot of RAM
#sudo cat "tmpfs /var/cache/pbuilder tmpfs defaults,size=6000M 0 0" >> /etc/fstab
#sudo mount /var/cache/pbuilder
#sudo mkdir /var/cache/pbuilder/aptcache

# Create build environment that will be chroot'ed into during packaging
#sudo apt install pbuilder cowbuilder
#sudo pbuilder create --distribution $DIST
#sudo cowbuilder --create --distribution $DIST
#sudo ln -s /var/cache/pbuilder/base.cow /var/cache/pbuilder/base-$DIST.cow

# Install build deps
# sudo apt install debhelper-compat dh-sequence-golang golang-github-alecaivazis-survey-dev \
#   golang-github-bmatcuk-doublestar-dev golang-github-dop251-goja-dev golang-github-fatih-color-dev \
#   golang-github-fsnotify-fsnotify-dev golang-github-spf13-cobra-dev golang-golang-x-sys-dev \
#   golang-golang-x-term-dev qt6-declarative-dev-tools golang-github-go-sourcemap-sourcemap-dev \
#   golang-github-google-pprof-dev

# build
pushd ..
sudo cowbuilder build --distribution $DIST --hookdir $(pwd)/debian/pbuilderhook.d ../prasmoid_0.0.3-1.dsc

# check result
# lintian ../*source.changes

# sign
# debsign ../*source.changes

# upload
# dput ppa:northern-lights/prasmoid ../*source.changes

popd

# cannot find package "github.com/adrg/frontmatter" in any of:
#         /usr/lib/go-1.24/src/github.com/adrg/frontmatter (from $GOROOT)
#         /build/prasmoid-0.0.3/_build/src/github.com/adrg/frontmatter (from $GOPATH)
