name: prasmoid
adopt-info: metadata
base: core22
version: 'v0.1.0'
license: 'MIT'
contact:
  - clem@lorteau.fr
  - https://github.com/PRASSamin/prasmoid
website:
  - https://github.com/PRASSamin/prasmoid
issues:
  - https://github.com/PRASSamin/prasmoid/issues
source-code:
  - https://github.com/PRASSamin/prasmoid/archive/refs/tags/v0.1.0.tar.gz

summary: The All in One Development Toolkit for KDE Plasmoids

grade: stable
confinement: strict

apps:
  prasmoid:
    command: prasmoid
    plugs:
       - home #users will not be able to create projects outside of their home folder
parts:
  repo:
    source: https://github.com/PRASSamin/prasmoid.git
    source-tag: v0.1.0
    plugin: dump
    override-build: |
      mv logo.svg io.github.prassamin.prasmoid.svg
      craftctl default

  binary:
    source: https://github.com/PRASSamin/prasmoid/releases/download/v0.1.0/prasmoid
    source-checksum: sha256/be4cf0af3d1ca42e2a0355b8b7c5e68a835bcc59a9ffcdbff143d7df3b5a1b97
    source-type: file
    plugin: dump
    override-build: |
      chmod +x prasmoid
      craftctl default
    prime:
      - prasmoid
    build-attributes:
      - enable-patchelf

  metadata:
    plugin: dump
    source-type: local
    source: .
    parse-info:
      - io.github.prassamin.prasmoid.metainfo.xml
