# last update 20250808

name: prasmoid
adopt-info: metadata
base: core22 # current=core24, keeping a bit of backwards compatibility since prasmoid
             # depends on nothing
version: 'v0.0.3'
license: 'MIT'

summary: The All in One Development Toolkit for KDE Plasmoids

grade: stable # must be 'stable' to release into candidate/stable channels
# confinement: devmode
confinement: strict

apps:
  prasmoid:
    command: prasmoid
    plugs:
      - home #allow r/w in the user's home dir
             #remember this if people are having issues writing somewhere else
             #install with snap install --devmode --dangerous to allow all the regular's
             #user's access

parts:
  repo:
    source: https://github.com/PRASSamin/prasmoid.git
    source-tag: v0.0.3
    plugin: dump #just copy files, nothing fancy
    override-build: |
      mv logo.svg org.prasmoid.prasmoid.svg
      craftctl default

  binary:
    source: https://github.com/PRASSamin/prasmoid/releases/download/v0.0.3/prasmoid
    source-checksum: sha256/72e4c2b772188ff7ac3ac1b210238a2b9aff1ef8a2844f11df999a44990dcc96
    source-type: file #don't try to guess what to do with the source and do nothing but d/l files
    plugin: dump
    override-build: |
      chmod +x prasmoid
      craftctl default
    prime:
      - prasmoid # copies the file to the snap's root where the "command" tag above will pick it up

  metadata:
    plugin: dump
    source-type: local
    source: .
    parse-info:
      - org.prasmoid.prasmoid.metainfo.xml
