name: prasmoid
adopt-info: metadata
base: core22
version: 'v0.0.4'
license: 'MIT'

summary: The All in One Development Toolkit for KDE Plasmoids

grade: stable
confinement: classic # for generating config and self updating

apps:
  prasmoid:
    command: prasmoid
    # plugs:
    #   - home

parts:
  repo:
    source: https://github.com/PRASSamin/prasmoid.git
    source-tag: v0.0.4
    plugin: dump
    override-build: |
      mv logo.svg io.github.prassamin.prasmoid.svg
      craftctl default

  binary:
    source: https://github.com/PRASSamin/prasmoid/releases/download/v0.0.4/prasmoid
    source-checksum: sha256/90b0db543e27c82aa32ad1b67410a37b375a82638b48a3301e774be10e44af93
    source-type: file
    plugin: dump
    override-build: |
      chmod +x prasmoid
      craftctl default
    prime:
      - prasmoid
    build-attributes:
      - enable-patchelf

  metadata:
    plugin: dump
    source-type: local
    source: .
    parse-info:
      - io.github.prassamin.prasmoid.metainfo.xml
