#!/bin/sh
#TODO: package these dependencies individually and include as proper deb build-deps
#	   otherwise package won't be accepted in official channels
#	   - github.com/adrg/frontmatter v0.2.0
#	   - github.com/dop251/goja v0.0.0-20250630131328-58d95d85e994
#	   - github.com/dop251/goja_nodejs v0.0.0-20250409162600-f7acab6894b0
echo "**Adding extra build deps"
ln -s $BUILDDIR/prasmoid-0.0.3/debian/src/github.com /usr/share/go-1.24/src/github.com

# a unit test fails if qmlformat isn't in the path
ln -s /lib/qt6/bin/qmlformat /usr/bin/qmlformat
